# Generated by Django 5.0 on 2023-12-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='markdowncontent',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
